### PR TITLE
denise hostmann first commit halloween

### PR DESCRIPTION
**Pull request by deniseddi**

### CODE REVIEW

**Comment by jamesformica** [comment]
got some merge conflicts here, let me know if you need any help

**Comment by linda-lai** [comment]
@deniseddi shout out if you need a hand with resolving the merge conflict :)

**Comment by ericjiang97** [comment]
we should really gitignore those .DS_Store files

**Review by josh- — APPROVED** [review]
Thanks so much @deniseddi! Wishing you a Happy Halloween too! 🎃

**Pull request merged**
