### PR TITLE
Added "naveen-bassi"

### PR DESCRIPTION
**Pull request by nav33nb**
Added webpage

### CODE REVIEW

**Comment by jamesformica** [comment]
Is `PHP` going to correctly work on Github Pages? This is just a simple static site

**Review by josh- — CHANGES_REQUESTED** [review]
Yeah unfortunately GitHub Pages doesn't support PHP @nav33nb 😞 it looks like we could definitely write this in client-side JavaScript so let us know if you'd like a hand to do that! 🎉

**Review by nav33nb — COMMENTED** [review]
Updated files in latest commit 
No more `PHP` :)

**Review by josh- — APPROVED** [review]
Looks fantastic, great work and thanks so much @nav33nb! 🙌🎉

**Pull request merged**
